// import Footer from './Footer';
import Accordion from './accordion';
import Overlay from './overlay';
import Modal from './modal';
import Nav from './nav';
import Scroll from './scroll';
import Search from './search';
import Slider from './slider';
import Sticky from './sticky';
import Utils from './utils';
import InternalNav from './internal_nav';
import CompactPanel from './compact_panel';
import MobileFilters from './mobile_filters';
import ListFilter from './list_filter';
import AddIcon from './add_icon';
import SearchSubmit from './search_submit';
import TagFilter from './tag_filter';
import Spectrum from './spectrum';
import CookiesPopup from './cookies_popup';

// Footer.init();
Accordion.init();
Modal.init();
Nav.init();
Overlay.init();
Scroll.init();
Search.init();
Slider.init();
Sticky.init();
Utils.markdownLinksNewPage();
InternalNav.init();
CompactPanel.init();
MobileFilters.init();
ListFilter.init();
AddIcon.init();
SearchSubmit.init();
TagFilter.init();
Spectrum.init();
CookiesPopup.init();
