// import Footer from './Footer';
import Accordion from './accordion';
import Overlay from './overlay';
import Modal from './modal';
import Nav from './nav';
import Scroll from './scroll';
import Search from './search';
import Slider from './slider';
import Sticky from './sticky';
import Utils from './utils';
import InternalNav from './internal_nav';
import CompactPanel from './compact_panel';
import FilterDropdown from './filter_dropdown';
import ListFilter from './list_filter';

// Footer.init();
Accordion.init();
Modal.init();
Nav.init();
Overlay.init();
Scroll.init();
Search.init();
Slider.init();
Sticky.init();
Utils.markdownLinksNewPage();
InternalNav.init();
CompactPanel.init();
FilterDropdown.init();
ListFilter.init();
