name: Jekyll Build on Contentful Publish Event
on:
  workflow_dispatch:
  repository_dispatch:
    types: [publish-event]
jobs:
  call-build-workflow:
    uses: ./.github/workflows/build.yml
    secrets:
      ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      OSHWA_CONTENTFUL_SPACE_ID: ${{ secrets.OSHWA_CONTENTFUL_SPACE_ID }}
      OSHWA_CONTENTFUL_DELIVERY_TOKEN: ${{ secrets.OSHWA_CONTENTFUL_DELIVERY_TOKEN }}
